import { createElement } from 'lucide';
import {
  Activity,
  AlertTriangle,
  Bell,
  Building2,
  CalendarDays,
  Check,
  ChevronsLeft,
  ChevronsRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coffee,
  FileSpreadsheet,
  FileText,
  HeartPulse,
  HelpCircle,
  House,
  LayoutDashboard,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Ellipsis,
  TreePalm,
  Pencil,
  Plus,
  ScrollText,
  Search,
  Settings,
  Share2,
  Shield,
  Smartphone,
  Timer,
  Trash2,
  User,
  UserCheck,
  UserRound,
  Users,
  Warehouse,
  X,
} from 'lucide';

const ICONS = {
  activity: Activity,
  alert: AlertTriangle,
  assignments: ClipboardList,
  attendance: Clock,
  audit: ScrollText,
  billing: FileSpreadsheet,
  bell: Bell,
  'building-2': Building2,
  calendar: CalendarDays,
  candidates: UserRound,
  check: Check,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  clipboard: ClipboardList,
  clock: Clock,
  coffee: Coffee,
  dashboard: LayoutDashboard,
  'file-text': FileText,
  health: HeartPulse,
  help: HelpCircle,
  home: House,
  hosts: Warehouse,
  leave: TreePalm,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  more: Ellipsis,
  organisations: Building2,
  pencil: Pencil,
  plus: Plus,
  profile: User,
  reports: FileSpreadsheet,
  schedule: CalendarDays,
  schedules: CalendarDays,
  search: Search,
  share: Share2,
  security: Shield,
  smartphone: Smartphone,
  settings: Settings,
  sites: MapPin,
  timer: Timer,
  trash: Trash2,
  user: User,
  'user-check': UserCheck,
  users: Users,
  warehouse: Warehouse,
  x: X,
  approvals: ClipboardCheck,
  alerts: Bell,
  notifications: Bell,
};

export const VIEW_ICONS = {
  dashboard: 'dashboard',
  home: 'home',
  organisations: 'organisations',
  users: 'users',
  hosts: 'hosts',
  candidates: 'candidates',
  sites: 'sites',
  assignments: 'assignments',
  schedules: 'schedules',
  schedule: 'schedule',
  attendance: 'attendance',
  leave: 'leave',
  approvals: 'approvals',
  reports: 'reports',
  audit: 'audit',
  billing: 'billing',
  settings: 'settings',
  security: 'security',
  health: 'health',
  notifications: 'bell',
  alerts: 'bell',
  profile: 'profile',
  legal: 'file-text',
};

export function icon(name, { size = 20, className = '', stroke = 2 } = {}) {
  const node = ICONS[name] || Clock;
  return createElement(node, {
    width: String(size),
    height: String(size),
    class: `ck-icon ${className}`.trim(),
    'stroke-width': String(stroke),
    'aria-hidden': 'true',
  });
}

export function viewIcon(view, opts) {
  return icon(VIEW_ICONS[view] || 'clock', opts);
}
